// This file is auto-generated by @hey-api/openapi-ts

import type {
  Options as ClientOptions,
  TDataShape,
  Client,
} from '@hey-api/client-axios'
import type {
  PostUserSignUpData,
  PostUserSignUpResponse,
  PostUserSignUpError,
  PostUserSignInData,
  PostUserSignInResponse,
  PostUserSignInError,
  GetUserProfileData,
  GetUserProfileResponse,
  GetUserProfileError,
  PatchUserProfileData,
  PatchUserProfileResponse,
  PatchUserProfileError,
  GetUserByIdData,
  GetUserByIdResponse,
  GetUserByIdError,
  GetExhibitData,
  GetExhibitResponse,
  PostExhibitData,
  PostExhibitResponse,
  PostExhibitError,
  GetExhibitByIdData,
  GetExhibitByIdResponse,
  GetExhibitByIdError,
  PatchExhibitByIdData,
  PatchExhibitByIdResponse,
  PatchExhibitByIdError,
  PostTableByNumberClaimData,
  PostTableByNumberClaimResponse,
  PostTableByNumberClaimError,
  PostTableByNumberReleaseData,
  PostTableByNumberReleaseResponse,
  PostTableByNumberReleaseError,
  PostTableByNumberAssignToByUserIdData,
  PostTableByNumberAssignToByUserIdResponse,
  PostTableByNumberAssignToByUserIdError,
} from './types.gen'
import { client as _heyApiClient } from './client.gen'

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = ClientOptions<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

/**
 * Create a user account
 */
export const postUserSignUp = <ThrowOnError extends boolean = false>(
  options: Options<PostUserSignUpData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostUserSignUpResponse,
    PostUserSignUpError,
    ThrowOnError
  >({
    url: '/user/sign-up',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Log in
 */
export const postUserSignIn = <ThrowOnError extends boolean = false>(
  options: Options<PostUserSignInData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostUserSignInResponse,
    PostUserSignInError,
    ThrowOnError
  >({
    url: '/user/login',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Retrieve the profile of the currently logged in user
 */
export const getUserProfile = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserProfileData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetUserProfileResponse,
    GetUserProfileError,
    ThrowOnError
  >({
    url: '/user/profile',
    ...options,
  })
}

/**
 * Update user account
 */
export const patchUserProfile = <ThrowOnError extends boolean = false>(
  options?: Options<PatchUserProfileData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).patch<
    PatchUserProfileResponse,
    PatchUserProfileError,
    ThrowOnError
  >({
    url: '/user/profile',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Retrieve the profile of the user identified by ID
 */
export const getUserById = <ThrowOnError extends boolean = false>(
  options: Options<GetUserByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetUserByIdResponse,
    GetUserByIdError,
    ThrowOnError
  >({
    url: '/user/{id}',
    ...options,
  })
}

/**
 * Retrieve list of all exhibits
 */
export const getExhibit = <ThrowOnError extends boolean = false>(
  options?: Options<GetExhibitData, ThrowOnError>,
) => {
  return (options?.client ?? _heyApiClient).get<
    GetExhibitResponse,
    unknown,
    ThrowOnError
  >({
    url: '/exhibit/',
    ...options,
  })
}

/**
 * Create exhibit
 */
export const postExhibit = <ThrowOnError extends boolean = false>(
  options: Options<PostExhibitData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostExhibitResponse,
    PostExhibitError,
    ThrowOnError
  >({
    url: '/exhibit/',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Retrieve a single exhibit
 */
export const getExhibitById = <ThrowOnError extends boolean = false>(
  options: Options<GetExhibitByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).get<
    GetExhibitByIdResponse,
    GetExhibitByIdError,
    ThrowOnError
  >({
    url: '/exhibit/{id}',
    ...options,
  })
}

/**
 * Update the properties of an exhibit
 */
export const patchExhibitById = <ThrowOnError extends boolean = false>(
  options: Options<PatchExhibitByIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).patch<
    PatchExhibitByIdResponse,
    PatchExhibitByIdError,
    ThrowOnError
  >({
    url: '/exhibit/{id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options?.headers,
    },
  })
}

/**
 * Claim a table to associate it with the current user
 */
export const postTableByNumberClaim = <ThrowOnError extends boolean = false>(
  options: Options<PostTableByNumberClaimData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostTableByNumberClaimResponse,
    PostTableByNumberClaimError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/table/{number}/claim',
    ...options,
  })
}

/**
 * Release a table so that it can be claimed by another user
 */
export const postTableByNumberRelease = <ThrowOnError extends boolean = false>(
  options: Options<PostTableByNumberReleaseData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostTableByNumberReleaseResponse,
    PostTableByNumberReleaseError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/table/{number}/release',
    ...options,
  })
}

/**
 * Assign a table to a user
 */
export const postTableByNumberAssignToByUserId = <
  ThrowOnError extends boolean = false,
>(
  options: Options<PostTableByNumberAssignToByUserIdData, ThrowOnError>,
) => {
  return (options.client ?? _heyApiClient).post<
    PostTableByNumberAssignToByUserIdResponse,
    PostTableByNumberAssignToByUserIdError,
    ThrowOnError
  >({
    security: [
      {
        scheme: 'bearer',
        type: 'http',
      },
    ],
    url: '/table/{number}/assign-to/{userId}',
    ...options,
  })
}
