services:
  powerdns:
    build: .
    container_name: powerdns
    ports:
      - "${PDNS_PORT}:53/tcp"
      - "${PDNS_PORT}:53/udp"
      - "8081:8081"
    environment:
      - PDNS_LAUNCH=gpgsql
      - PDNS_GPGSQL_HOST=host.docker.internal
      - PDNS_GPGSQL_PORT=5432
      - PDNS_GPGSQL_USER=pdns
      - PDNS_GPGSQL_PASSWORD=${PDNS_PASSWORD}
      - PDNS_GPGSQL_DBNAME=exhibitron
      - PDNS_API_KEY=${PDNS_API_KEY}
    volumes:
      - ./pdns.conf.template:/etc/powerdns/pdns.conf.template
    restart: unless-stopped
