services:
  powerdns:
    build: .
    container_name: powerdns
    ports:
      - "5300:53/tcp"
      - "5300:53/udp"
      - "8081:8081"
    environment:
      - PDNS_launch=gpgsql
      - PDNS_gpgsql_host=host.docker.internal
      - PDNS_gpgsql_port=5432
      - PDNS_gpgsql_user=pdns
      - PDNS_gpgsql_password=${PDNS_PASSWORD}
      - PDNS_gpgsql_dbname=exhibitron
      - PDNS_API_KEY=${PDNS_API_KEY}
    volumes:
      - ./pdns.conf:/etc/powerdns/pdns.conf
    restart: unless-stopped 
