services:
  powerdns:
    build: .
    container_name: powerdns
    ports:
      - "${PDNS_PORT}:53/tcp"
      - "${PDNS_PORT}:53/udp"
      - "8081:8081"
    environment:
      - PDNS_LAUNCH=gpgsql
      - PDNS_GPGSQL_HOST=${PGHOST}
      - PDNS_GPGSQL_PORT=${PGPORT}
      - PDNS_GPGSQL_USER=${PGUSER}
      - PDNS_GPGSQL_PASSWORD=${PGPASSWORD}
      - PDNS_GPGSQL_DBNAME=exhibitron
      - PDNS_API_KEY=${PDNS_API_KEY}
    volumes:
      - ./pdns.conf.template:/etc/powerdns/pdns.conf.template
    restart: unless-stopped
